#define _GNU_SOURCE

#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <fnmatch.h>
#include <locale.h>
#include <math.h>
#include <pthread.h>
#include <sched.h>
#include <signal.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>
#include <utime.h>
#include <wchar.h>
#include <wctype.h>

#include <EGL/egl.h>
#include <GLES2/gl2.h>
#include <switch.h>
#include <zlib.h>

#include "android_shim.h"
#include "bionic_shim.h"
#include "egl_shim.h"
#include "imports.h"
#include "ib3_shim.h"
#include "libc_shim.h"
#include "so_util.h"
#include "util.h"

#define MAP(name) {#name, (uintptr_t)&name}
#define MAP_TO(name, target) {name, (uintptr_t)&target}

extern void __stack_chk_fail(void);
static void *fake_stdin = &fake_sF[0];
static void *fake_stderr = &fake_sF[2];

static int fseeko64_fake(FILE *stream, int64_t offset, int origin) {
  return fseeko(stream, (off_t)offset, origin);
}

static int getpid_fake(void) { return 1; }

static int pthread_attribute_noop(void *attribute, ...) {
  (void)attribute;
  return 0;
}

static int log_noop(void) { return 0; }

static void sincosf_compat(float value, float *sine, float *cosine) {
  if (sine)
    *sine = sinf(value);
  if (cosine)
    *cosine = cosf(value);
}

DynLibFunction dynlib_functions[] = {
    MAP_TO("AAssetDir_close", AAssetDir_close_fake),
    MAP_TO("AAssetDir_getNextFileName", AAssetDir_getNextFileName_fake),
    MAP_TO("AAssetManager_open", AAssetManager_open_fake),
    MAP_TO("AAssetManager_openDir", AAssetManager_openDir_fake),
    MAP_TO("AAsset_close", AAsset_close_fake),
    MAP_TO("AAsset_openFileDescriptor64", AAsset_openFileDescriptor64_fake),
    MAP_TO("AConfiguration_delete", AConfiguration_delete_fake),
    MAP_TO("AConfiguration_fromAssetManager", AConfiguration_fromAssetManager_fake),
    MAP_TO("AConfiguration_getCountry", AConfiguration_getCountry_fake),
    MAP_TO("AConfiguration_getDensity", AConfiguration_getDensity_fake),
    MAP_TO("AConfiguration_getLanguage", AConfiguration_getLanguage_fake),
    MAP_TO("AConfiguration_new", AConfiguration_new_fake),
    MAP_TO("AInputEvent_getType", AInputEvent_getType_fake),
    MAP_TO("AInputQueue_attachLooper", AInputQueue_attachLooper_fake),
    MAP_TO("AInputQueue_detachLooper", AInputQueue_detachLooper_fake),
    MAP_TO("AInputQueue_finishEvent", AInputQueue_finishEvent_fake),
    MAP_TO("AInputQueue_getEvent", AInputQueue_getEvent_fake),
    MAP_TO("AInputQueue_preDispatchEvent", AInputQueue_preDispatchEvent_fake),
    MAP_TO("ALooper_addFd", ALooper_addFd_fake),
    MAP_TO("ALooper_pollOnce", ALooper_pollOnce_fake),
    MAP_TO("ALooper_prepare", ALooper_prepare_fake),
    MAP_TO("AMotionEvent_getAction", AMotionEvent_getAction_fake),
    MAP_TO("AMotionEvent_getEventTime", AMotionEvent_getEventTime_fake),
    MAP_TO("AMotionEvent_getPointerCount", AMotionEvent_getPointerCount_fake),
    MAP_TO("AMotionEvent_getPointerId", AMotionEvent_getPointerId_fake),
    MAP_TO("AMotionEvent_getX", AMotionEvent_getX_fake),
    MAP_TO("AMotionEvent_getY", AMotionEvent_getY_fake),
    MAP_TO("ANativeActivity_setWindowFlags", ANativeActivity_setWindowFlags_fake),
    MAP_TO("ANativeWindow_setBuffersGeometry", ANativeWindow_setBuffersGeometry_fake),

    MAP_TO("__android_log_print", android_log_print_fake),
    MAP_TO("__assert2", assert2_fake),
    MAP_TO("__cxa_atexit", cxa_atexit_fake),
    MAP_TO("__cxa_finalize", cxa_finalize_fake),
    MAP_TO("__cxa_thread_atexit_impl", __cxa_thread_atexit_impl_fake),
    MAP_TO("__ctype_get_mb_cur_max", __ctype_get_mb_cur_max_fake),
    MAP_TO("__errno", errno_fake),
    MAP_TO("__memcpy_chk", __memcpy_chk_fake),
    MAP_TO("__register_atfork", __register_atfork_fake),
    MAP_TO("__sF", fake_sF),
    MAP(__stack_chk_fail),
    MAP_TO("__strcat_chk", __strcat_chk_fake),
    MAP_TO("__strcpy_chk", __strcpy_chk_fake),
    MAP_TO("__strlen_chk", __strlen_chk_fake),
    MAP_TO("__system_property_get", __system_property_get_fake),
    MAP_TO("__vsnprintf_chk", __vsnprintf_chk_fake),
    MAP_TO("_exit", exit_fake),
    MAP(abort),
    MAP_TO("android_set_abort_message", android_set_abort_message_fake),

    MAP_TO("access", access_fake),
    MAP(acosf),
    MAP(asinf),
    MAP(atan2f),
    MAP(atanf),
    MAP(atof),
    MAP(atoi),
    MAP(calloc),
    MAP(cbrtf),
    MAP(chdir),
    MAP(chmod),
    MAP_TO("clock_gettime", clock_gettime_fake),
    MAP_TO("close", close_dispatch_fake),
    MAP(closedir),
    MAP_TO("closelog", log_noop),
    MAP(compress),
    MAP(cos),
    MAP(cosf),
    MAP(difftime),
    MAP_TO("dl_iterate_phdr", so_dl_iterate_phdr),
    MAP_TO("dlclose", dlclose_fake),
    MAP_TO("dlerror", dlerror_fake),
    MAP_TO("dlopen", dlopen_fake),
    MAP_TO("dlsym", dlsym_fake),

    MAP(eglBindAPI),
    MAP_TO("eglChooseConfig", eglChooseConfig_fake),
    MAP_TO("eglCreateContext", eglCreateContext_fake),
    MAP_TO("eglCreateWindowSurface", eglCreateWindowSurface_fake),
    MAP(eglCreatePbufferSurface),
    MAP(eglDestroyContext),
    MAP(eglDestroySurface),
    MAP(eglGetConfigAttrib),
    MAP(eglGetCurrentContext),
    MAP(eglGetCurrentSurface),
    MAP_TO("eglGetDisplay", eglGetDisplay_fake),
    MAP(eglGetError),
    MAP(eglGetProcAddress),
    MAP_TO("eglInitialize", eglInitialize_fake),
    MAP_TO("eglMakeCurrent", eglMakeCurrent_fake),
    MAP_TO("eglQuerySurface", eglQuerySurface_fake),
    MAP_TO("eglSwapBuffers", eglSwapBuffers_fake),
    MAP_TO("eglSwapInterval", eglSwapInterval_fake),

    MAP_TO("exit", exit_fake),
    MAP(exp2f),
    MAP(expf),
    MAP_TO("fclose", fclose_fake),
    MAP(fdopen),
    MAP_TO("fflush", fflush_fake),
    MAP(fgets),
    MAP(fmodf),
    MAP(fnmatch),
    MAP_TO("fopen", fopen_fake),
    MAP_TO("fprintf", fprintf_fake),
    MAP_TO("fputc", fputc_fake),
    MAP_TO("fputs", fputs_fake),
    MAP(fputwc),
    MAP_TO("fread", fread_fake),
    MAP(freelocale),
    MAP(frexpf),
    MAP(free),
    MAP(fscanf),
    MAP_TO("fseek", fseek_fake),
    MAP(fseeko),
    MAP_TO("fseeko64", fseeko64_fake),
    MAP(ftell),
    MAP(ftello),
    MAP_TO("fwrite", fwrite_fake),
    MAP_TO("getc", getc_fake),
    MAP(getcwd),
    MAP(getpid_fake),
    MAP_TO("getpid", getpid_fake),
    MAP_TO("gettid", gettid_fake),
    MAP(gettimeofday),
    MAP_TO("getauxval", getauxval_fake),
    MAP(getenv),
    MAP(getwc),
    MAP(gmtime_r),
    MAP(hypotf),
    MAP_TO("iswlower_l", iswlower_l_fake),
    MAP(iswpunct),
    MAP(ldexp),
    MAP(ldexpf),
    MAP(localtime_r),
    MAP(log10f),
    MAP(log2f),
    MAP(logf),
    MAP(malloc),
    MAP(mbrlen),
    MAP(mbrtowc),
    MAP_TO("mbsnrtowcs", mbsnrtowcs_fake),
    MAP(mbsrtowcs),
    MAP(mbtowc),
    MAP(memchr),
    MAP(memcmp),
    MAP(memcpy),
    MAP(memmove),
    MAP(memset),
    MAP(mkdir),
    MAP(modf),
    MAP_TO("nanosleep", nanosleep_fake),
    MAP_TO("newlocale", newlocale_fake),
    MAP(opendir),
    MAP_TO("openlog", log_noop),
    MAP_TO("pathconf", pathconf_fake),
    MAP_TO("pipe", pipe_fake),
    MAP_TO("posix_memalign", posix_memalign_fake),
    MAP(powf),
    MAP_TO("printf", debugPrintf),

    MAP_TO("pthread_attr_destroy", pthread_attribute_noop),
    MAP_TO("pthread_attr_init", pthread_attribute_noop),
    MAP_TO("pthread_attr_setdetachstate", pthread_attribute_noop),
    MAP_TO("pthread_attr_setstacksize", pthread_attribute_noop),
    MAP_TO("pthread_cond_broadcast", pthread_cond_broadcast_fake),
    MAP_TO("pthread_cond_destroy", pthread_cond_destroy_fake),
    MAP_TO("pthread_cond_init", pthread_cond_init_fake),
    MAP_TO("pthread_cond_signal", pthread_cond_signal_fake),
    MAP_TO("pthread_cond_timedwait", pthread_cond_timedwait_fake),
    MAP_TO("pthread_cond_wait", pthread_cond_wait_fake),
    MAP_TO("pthread_create", pthread_create_fake),
    MAP_TO("pthread_detach", pthread_detach_fake),
    MAP_TO("pthread_getspecific", pthread_getspecific_fake),
    MAP(pthread_join),
    MAP_TO("pthread_key_create", pthread_key_create_fake),
    MAP_TO("pthread_key_delete", pthread_key_delete_fake),
    MAP_TO("pthread_mutex_destroy", pthread_mutex_destroy_fake),
    MAP_TO("pthread_mutex_init", pthread_mutex_init_fake),
    MAP_TO("pthread_mutex_lock", pthread_mutex_lock_fake),
    MAP_TO("pthread_mutex_unlock", pthread_mutex_unlock_fake),
    MAP_TO("pthread_mutexattr_destroy", pthread_attribute_noop),
    MAP_TO("pthread_mutexattr_init", pthread_attribute_noop),
    MAP_TO("pthread_mutexattr_settype", pthread_attribute_noop),
    MAP_TO("pthread_once", pthread_once_fake),
    MAP_TO("pthread_rwlock_rdlock", pthread_rwlock_rdlock_fake),
    MAP_TO("pthread_rwlock_unlock", pthread_rwlock_unlock_fake),
    MAP_TO("pthread_rwlock_wrlock", pthread_rwlock_wrlock_fake),
    MAP(pthread_self),
    MAP_TO("pthread_setname_np", pthread_setname_np_fake),
    MAP_TO("pthread_setschedparam", pthread_setschedparam_fake),
    MAP_TO("pthread_setspecific", pthread_setspecific_fake),

    MAP(qsort),
    MAP(raise),
    MAP(rand),
    MAP_TO("read", read_dispatch_fake),
    MAP(readdir_fake),
    MAP_TO("readdir", readdir_fake),
    MAP(readlink),
    MAP(realloc),
    MAP(rename),
    MAP(rmdir),
    MAP_TO("sched_get_priority_max", ret0),
    MAP_TO("sched_get_priority_min", ret0),
    MAP_TO("sched_yield", sched_yield_fake),
    MAP_TO("sincos", sincos_fake),
    MAP_TO("sincosf", sincosf_compat),
    MAP(sin),
    MAP(sinf),
    MAP(sinhf),
    MAP_TO("sleep", sleep_fake),
    MAP(snprintf),
    MAP(srand),
    MAP(sscanf),
    MAP_TO("stat", stat_fake),
    MAP_TO("stdin", fake_stdin),
    MAP_TO("stdout", fake_stdout),
    MAP(strcasecmp),
    MAP(strcmp),
    MAP(strcpy),
    MAP(strerror),
    MAP_TO("strerror_r", strerror_r_fake),
    MAP(strftime_l_fake),
    MAP_TO("strftime_l", strftime_l_fake),
    MAP(strlen),
    MAP(strncmp),
    MAP(strncpy),
    MAP(strtod),
    MAP(strtof),
    MAP(strtol),
    MAP_TO("strtold_l", strtold_l_fake),
    MAP(strtoll),
    MAP_TO("strtoll_l", strtoll_l_fake),
    MAP(strtoul),
    MAP_TO("strtoull_l", strtoull_l_fake),
    MAP_TO("syscall", syscall_fake),
    MAP_TO("sysconf", sysconf_fake),
    MAP_TO("syslog", log_noop),
    MAP(tanf),
    MAP(time),
    MAP(uncompress),
    MAP_TO("ungetc", ungetc_fake),
    MAP(ungetwc),
    MAP(unlink),
    MAP_TO("uselocale", uselocale_fake),
    MAP_TO("usleep", usleep_fake),
    MAP(utime),
    MAP(vasprintf),
    MAP_TO("vfprintf", vfprintf_fake),
    MAP(vsnprintf),
    MAP(vsscanf),
    MAP(wcrtomb),
    MAP(wcslen),
    MAP_TO("wcsnrtombs", wcsnrtombs_fake),
    MAP(wmemchr),
    MAP_TO("write", write_dispatch_fake),

    MAP(glActiveTexture),
    MAP(glAttachShader),
    MAP(glBindBuffer),
    MAP(glBindFramebuffer),
    MAP(glBindRenderbuffer),
    MAP(glBindTexture),
    MAP(glBlendColor),
    MAP(glBlendEquationSeparate),
    MAP(glBlendFuncSeparate),
    MAP(glBufferData),
    MAP(glBufferSubData),
    MAP(glCheckFramebufferStatus),
    MAP(glClear),
    MAP(glClearColor),
    MAP(glClearDepthf),
    MAP(glClearStencil),
    MAP(glColorMask),
    MAP(glCompileShader),
    MAP(glCompressedTexImage2D),
    MAP(glCreateProgram),
    MAP(glCreateShader),
    MAP(glDeleteBuffers),
    MAP(glDeleteProgram),
    MAP(glDeleteShader),
    MAP(glDeleteTextures),
    MAP(glDepthFunc),
    MAP(glDepthMask),
    MAP(glDepthRangef),
    MAP(glDetachShader),
    MAP(glDisable),
    MAP(glDisableVertexAttribArray),
    MAP_TO("glDrawArrays", glDrawArrays_fake),
    MAP_TO("glDrawElements", glDrawElements_fake),
    MAP(glEnable),
    MAP(glEnableVertexAttribArray),
    MAP(glFinish),
    MAP(glFramebufferRenderbuffer),
    MAP(glFramebufferTexture2D),
    MAP(glFrontFace),
    MAP(glGenBuffers),
    MAP(glGenFramebuffers),
    MAP(glGenRenderbuffers),
    MAP(glGenTextures),
    MAP(glGetAttribLocation),
    MAP(glGetBooleanv),
    MAP(glGetError),
    MAP(glGetIntegerv),
    MAP(glGetUniformLocation),
    MAP(glLinkProgram),
    MAP(glPixelStorei),
    MAP(glReadPixels),
    MAP(glRenderbufferStorage),
    MAP(glScissor),
    MAP(glShaderSource),
    MAP(glStencilFunc),
    MAP(glStencilMask),
    MAP(glStencilOp),
    MAP(glTexImage2D),
    MAP(glTexParameteri),
    MAP(glUniform1fv),
    MAP(glUniform1i),
    MAP(glUniform2fv),
    MAP(glUniform3fv),
    MAP(glUniform4fv),
    MAP(glUniformMatrix3fv),
    MAP(glUniformMatrix4fv),
    MAP(glUseProgram),
    MAP(glVertexAttribPointer),
    MAP_TO("glViewport", glViewport_fake),

    /* --- libib3.so (Infinity Blade III) additions --------------------- */
    MAP_TO("ANativeWindow_getHeight", ANativeWindow_getHeight_fake),
    MAP_TO("ANativeWindow_getWidth", ANativeWindow_getWidth_fake),
    MAP_TO("__memset_chk", __memset_chk_fake),
    MAP_TO("__strchr_chk", __strchr_chk_fake),
    MAP_TO("__strncpy_chk2", __strncpy_chk2_fake),
    MAP_TO("fcntl", fcntl_fake),
    MAP_TO("fstat", fstat_fake),
    MAP_TO("iswalpha_l", iswalpha_l_fake),
    MAP_TO("iswblank_l", iswblank_l_fake),
    MAP_TO("iswcntrl_l", iswcntrl_l_fake),
    MAP_TO("iswdigit_l", iswdigit_l_fake),
    MAP_TO("iswprint_l", iswprint_l_fake),
    MAP_TO("iswpunct_l", iswpunct_l_fake),
    MAP_TO("iswspace_l", iswspace_l_fake),
    MAP_TO("iswupper_l", iswupper_l_fake),
    MAP_TO("iswxdigit_l", iswxdigit_l_fake),
    MAP_TO("lstat", lstat_fake),
    MAP_TO("open", open_fake),
    MAP_TO("openat", openat_fake),
    MAP_TO("realpath", realpath_fake),
    MAP_TO("setbuf", setbuf_fake),
    MAP_TO("statvfs", statvfs_fake),
    MAP_TO("strcoll_l", strcoll_l_fake),
    MAP_TO("strxfrm_l", strxfrm_l_fake),
    MAP_TO("towlower_l", towlower_l_fake),
    MAP_TO("towupper_l", towupper_l_fake),
    MAP_TO("unlinkat", unlinkat_fake),
    MAP_TO("wcscoll_l", wcscoll_l_fake),
    MAP_TO("wcsxfrm_l", wcsxfrm_l_fake),
    MAP_TO("AAudioStreamBuilder_openStream", AAudioStreamBuilder_openStream_fake),
    MAP_TO("AAudioStreamBuilder_setChannelCount", AAudioStreamBuilder_setChannelCount_fake),
    MAP_TO("AAudioStreamBuilder_setFormat", AAudioStreamBuilder_setFormat_fake),
    MAP_TO("AAudioStreamBuilder_setPerformanceMode", AAudioStreamBuilder_setPerformanceMode_fake),
    MAP_TO("AAudioStreamBuilder_setSampleRate", AAudioStreamBuilder_setSampleRate_fake),
    MAP_TO("AAudioStreamBuilder_setUsage", AAudioStreamBuilder_setUsage_fake),
    MAP_TO("AAudioStream_close", AAudioStream_close_fake),
    MAP_TO("AAudioStream_getFramesPerBurst", AAudioStream_getFramesPerBurst_fake),
    MAP_TO("AAudioStream_getSampleRate", AAudioStream_getSampleRate_fake),
    MAP_TO("AAudioStream_requestStart", AAudioStream_requestStart_fake),
    MAP_TO("AAudioStream_write", AAudioStream_write_fake),
    MAP_TO("AAudio_createStreamBuilder", AAudio_createStreamBuilder_fake),
    MAP_TO("AInputEvent_getSource", AInputEvent_getSource_fake),
    MAP_TO("AKeyEvent_getAction", AKeyEvent_getAction_fake),
    MAP_TO("AKeyEvent_getKeyCode", AKeyEvent_getKeyCode_fake),
    MAP_TO("AKeyEvent_getRepeatCount", AKeyEvent_getRepeatCount_fake),
    MAP_TO("AMediaCodec_configure", AMediaCodec_configure_fake),
    MAP_TO("AMediaCodec_createDecoderByType", AMediaCodec_createDecoderByType_fake),
    MAP_TO("AMediaCodec_delete", AMediaCodec_delete_fake),
    MAP_TO("AMediaCodec_dequeueInputBuffer", AMediaCodec_dequeueInputBuffer_fake),
    MAP_TO("AMediaCodec_dequeueOutputBuffer", AMediaCodec_dequeueOutputBuffer_fake),
    MAP_TO("AMediaCodec_flush", AMediaCodec_flush_fake),
    MAP_TO("AMediaCodec_getInputBuffer", AMediaCodec_getInputBuffer_fake),
    MAP_TO("AMediaCodec_getOutputBuffer", AMediaCodec_getOutputBuffer_fake),
    MAP_TO("AMediaCodec_getOutputFormat", AMediaCodec_getOutputFormat_fake),
    MAP_TO("AMediaCodec_queueInputBuffer", AMediaCodec_queueInputBuffer_fake),
    MAP_TO("AMediaCodec_releaseOutputBuffer", AMediaCodec_releaseOutputBuffer_fake),
    MAP_TO("AMediaCodec_start", AMediaCodec_start_fake),
    MAP_TO("AMediaCodec_stop", AMediaCodec_stop_fake),
    MAP_TO("AMediaExtractor_advance", AMediaExtractor_advance_fake),
    MAP_TO("AMediaExtractor_delete", AMediaExtractor_delete_fake),
    MAP_TO("AMediaExtractor_getSampleTime", AMediaExtractor_getSampleTime_fake),
    MAP_TO("AMediaExtractor_getTrackCount", AMediaExtractor_getTrackCount_fake),
    MAP_TO("AMediaExtractor_getTrackFormat", AMediaExtractor_getTrackFormat_fake),
    MAP_TO("AMediaExtractor_new", AMediaExtractor_new_fake),
    MAP_TO("AMediaExtractor_readSampleData", AMediaExtractor_readSampleData_fake),
    MAP_TO("AMediaExtractor_seekTo", AMediaExtractor_seekTo_fake),
    MAP_TO("AMediaExtractor_selectTrack", AMediaExtractor_selectTrack_fake),
    MAP_TO("AMediaExtractor_setDataSourceFd", AMediaExtractor_setDataSourceFd_fake),
    MAP_TO("AMediaFormat_delete", AMediaFormat_delete_fake),
    MAP_TO("AMediaFormat_getBuffer", AMediaFormat_getBuffer_fake),
    MAP_TO("AMediaFormat_getInt32", AMediaFormat_getInt32_fake),
    MAP_TO("AMediaFormat_getInt64", AMediaFormat_getInt64_fake),
    MAP_TO("AMediaFormat_getRect", AMediaFormat_getRect_fake),
    MAP_TO("AMediaFormat_getString", AMediaFormat_getString_fake),
    MAP_TO("AMediaFormat_setInt32", AMediaFormat_setInt32_fake),
    MAP_TO("__open_2", __open_2_fake),
    MAP_TO("__read_chk", __read_chk_fake),
    MAP_TO("__readlink_chk", __readlink_chk_fake),
    MAP_TO("__write_chk", __write_chk_fake),
    MAP_TO("pread", pread_fake),
    MAP_TO("pwrite", pwrite_fake),
    MAP_TO("fsync", fsync_fake),
    MAP_TO("ftruncate", ftruncate_fake),
    MAP_TO("truncate", truncate_fake),
    MAP_TO("fchmod", fchmod_fake),
    MAP_TO("fchmodat", fchmodat_fake),
    MAP_TO("fchown", fchown_fake),
    MAP_TO("fdopendir", fdopendir_fake),
    MAP_TO("link", link_fake),
    MAP_TO("symlink", symlink_fake),
    MAP_TO("sendfile", sendfile_fake),
    MAP_TO("getrandom", getrandom_fake),
    MAP_TO("process_vm_readv", process_vm_readv_fake),
    MAP_TO("utimensat", utimensat_fake),
    MAP_TO("utimes", utimes_fake),
    MAP_TO("sysinfo", sysinfo_fake),
    MAP_TO("pthread_getattr_np", pthread_getattr_np_fake),
    MAP_TO("pthread_attr_getstack", pthread_attr_getstack_fake),
    MAP_TO("sigaction", sigaction_fake),
    MAP_TO("signal", signal_fake),
    MAP_TO("sigaltstack", sigaltstack_fake),
    MAP_TO("mmap", mmap_fake),
    MAP_TO("munmap", munmap_fake),
    MAP_TO("mprotect", mprotect_fake),
    MAP_TO("mremap", mremap_fake),
    MAP_TO("madvise", madvise_fake),
    MAP_TO("AAudioStreamBuilder_delete", AAudioStreamBuilder_delete_fake),
    MAP_TO("__android_log_write", android_log_write_fake),
    MAP_TO("lseek64", lseek),
    MAP_TO("pthread_mutex_trylock", pthread_mutex_trylock_fake),
    MAP_TO("pthread_cond_clockwait", pthread_cond_clockwait_fake),
    MAP_TO("stderr", fake_stderr),
    MAP_TO("AMEDIAFORMAT_KEY_WIDTH", ib3_amediaformat_key_width),
    MAP_TO("AMEDIAFORMAT_KEY_HEIGHT", ib3_amediaformat_key_height),
    MAP_TO("AMEDIAFORMAT_KEY_MIME", ib3_amediaformat_key_mime),
    MAP_TO("AMEDIAFORMAT_KEY_DURATION", ib3_amediaformat_key_duration),
    MAP_TO("AMEDIAFORMAT_KEY_STRIDE", ib3_amediaformat_key_stride),
    MAP_TO("AMEDIAFORMAT_KEY_SLICE_HEIGHT", ib3_amediaformat_key_slice_height),
    MAP_TO("AMEDIAFORMAT_KEY_COLOR_FORMAT", ib3_amediaformat_key_color_format),
    MAP_TO("AMEDIAFORMAT_KEY_DISPLAY_CROP", ib3_amediaformat_key_display_crop),
    MAP_TO("AMEDIAFORMAT_KEY_SAMPLE_RATE", ib3_amediaformat_key_sample_rate),
    MAP_TO("AMEDIAFORMAT_KEY_CHANNEL_COUNT", ib3_amediaformat_key_channel_count),
    MAP_TO("AMEDIAFORMAT_KEY_PCM_ENCODING", ib3_amediaformat_key_pcm_encoding),
    MAP(btowc),
    MAP(fmod),
    MAP(freopen),
    MAP(frexp),
    MAP(geteuid),
    MAP(iswalpha),
    MAP(iswlower),
    MAP(iswspace),
    MAP(iswupper),
    MAP(localeconv),
    MAP(localtime),
    MAP(mktime),
    MAP(remove),
    MAP(setenv),
    MAP(setlocale),
    MAP(strcat),
    MAP(strchr),
    MAP(strcspn),
    MAP(strncasecmp),
    MAP(strnlen),
    MAP(strrchr),
    MAP(strspn),
    MAP(strstr),
    MAP(strtold),
    MAP(strtoull),
    MAP(swprintf),
    MAP(towupper),
    MAP(unsetenv),
    MAP(wcstod),
    MAP(wcstof),
    MAP(wcstol),
    MAP(wcstold),
    MAP(wcstoll),
    MAP(wcstoul),
    MAP(wcstoull),
    MAP(wctob),
    MAP(wmemcmp),
};

const size_t dynlib_numfunctions =
    sizeof(dynlib_functions) / sizeof(dynlib_functions[0]);
